#include "configwindow.h"
#include "ui_configwindow.h"
#include <QApplication>
#include <QDebug>
#include <QTextStream>
#include <QDir>
#include <QDateTime>
#include <QFile>
#include <QtSerialPort/QSerialPort>
#include <QtSerialPort/QSerialPortInfo>
#include <QFile>
#include <QFileDialog>
#include <QCoreApplication>
#include <QTextStream>
#include <QThread>

ConfigWindow::ConfigWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::ConfigWindow)
{
    ui->setupUi(this);
}

ConfigWindow::~ConfigWindow()
{
    delete ui;
}

#ifdef Q_OS_WIN
#define PROGRAMS_PATH   "c:/Nevol_Presso_Resources/Programs"
#else
#define PROGRAMS_PATH   "/Devel/Stm32_18.1_A_os_2025.10-rc"
#endif


void ConfigWindow::Generate_Header()
{
    QDateTime currentDateTime = QDateTime::currentDateTime();
    QDate currentDate = currentDateTime.date();
    QTime currentTime = currentDateTime.time();
    QFile file(filename);
    QTextStream out(&file);
    if (file.open(QIODevice::WriteOnly))
    {
        out << "/* \n";
        out << "* This program is free software: you can redistribute it and/or modify  \n";
        out << "* it under the terms of the GNU General Public License as published by  \n";
        out << "* the Free Software Foundation, version 3.\n";
        out << "*\n";
        out << "* This program is distributed in the hope that it will be useful, but \n";
        out << "* WITHOUT ANY WARRANTY; without even the implied warranty of \n";
        out << "* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU \n";
        out << "* General Public License for more details.\n";
        out << "*\n";
        out << "* You should have received a copy of the GNU General Public License \n";
        out << "* along with this program. If not, see <http://www.gnu.org/licenses/>.\n";
        out << "*\n";
        out << "* Project : A_os\n";
        out << "* Generated by QtConfigurator\n";
        QString timestamp = "*  Created on: " + currentDate.toString("dd/MM/yy")+" "+currentTime.toString("hh:mm:ss");
        out << timestamp;
        out << "*/\n";
        out << "/*\n";
        out << "* user_config.h\n";
        out << "*/\n";
        out << "\n";
        out << "#ifndef PROJECT_LIB_MODULES_H_\n";
        out << "#define PROJECT_LIB_MODULES_H_\n";
        out << "\n";
        out << "#define		USER_PROCESSES	1\n";
        out << "\n";
        file.close();
    }
}

void ConfigWindow::Generate_Libraries()
{
    QFile file(filename);
    QTextStream out(&file);
    if (file.open(QIODevice::Append))
    {
        out << "/* Libraries */\n";
        if ( ui->Helix_checkBox->isChecked())
            out << "#define	HELIX_ENABLE	1\n";
        else
            out << "//#define	HELIX_ENABLE	1\n";
        if ( ui->LoraWAN_checkBox->isChecked())
            out << "#define	LORAWAN_ENABLE	1\n";
        else
            out << "//#define	LORAWAN_ENABLE	1\n";
        if ( ui->LwIp_checkBox->isChecked())
            out << "#define	LWIP_ENABLE		1\n";
        else
            out << "//#define	LWIP_ENABLE		1\n";
        if ( ui->WiFi_checkBox->isChecked())
            out << "#define	WIFI_ENABLE		1\n";

        out << "//#define	WIFI_ENABLE		1\n";
        out << "\n";
        out << "#ifdef LWIP_ENABLE\n";
        out << "    #define	NETWORKING_ENABLED		1\n";
        if ( ui->MQTT_checkBox->isChecked())
            out << "	#define	MQTT_ENABLE	1\n";
        else
            out << "	//#define	MQTT_ENABLE	1\n";
        out << "#endif // #ifdef LWIP_ENABLE\n";
        out << "#ifdef WIFI_ENABLE\n";
        out << "	#define	WIFI_ESP01S		1\n";
        out << "#endif // #ifdef WIFI_ENABLE\n";
        out << "\n";
        file.close();
    }
}

void ConfigWindow::Generate_Modules()
{
    QFile file(filename);
    QTextStream out(&file);
    if (file.open(QIODevice::Append))
    {
        out << "/* Modules */\n";
        if ( ui->HEX_DEC_checkBox->isChecked())
            out << "#define	HEX_DEC_ENABLE	1\n";
        else
            out << "//#define	HEX_DEC_ENABLE	1\n";
        if ( ui->XMODEM_checkBox->isChecked())
            out << "#define	XMODEM_ENABLE	1\n";
        else
            out << "//#define	XMODEM_ENABLE	1\n";
        if ( ui->MODBUS_checkBox->isChecked())
            out << "#define	MODBUS_ENABLE	1\n";
        else
            out << "//#define	MODBUS_ENABLE	1\n";
        if ( ui->SOUND_checkBox->isChecked())
            out << "#define	SOUND_ENABLED	1\n";
        else
            out << "//#define	SOUND_ENABLED	1\n";
        out << "\n";
        file.close();
    }
}

void ConfigWindow::Generate_Drivers()
{
    QFile file(filename);
    QTextStream out(&file);
    if (file.open(QIODevice::Append))
    {
        out << "/* drivers */\n";
        out << "\n";
        if ( ui->USB_checkBox->isChecked())
            out << "#define USB_DEVICE_ENABLED	1\n";
        else
            out << "//#define USB_DEVICE_ENABLED	1\n";
        out << "#ifdef USB_DEVICE_ENABLED\n";
        out << "    #define USB_"  << ui->USB_comboBox->currentText() << " 1\n";
        out << "#endif // #ifdef USB_ENABLED\n";

        if ( ui->LCD_checkBox->isChecked())
            out << "#define HAS_LCD 1\n";
        else
            out << "//#define HAS_LCD 1\n";
        out << "#ifdef HAS_LCD\n";
        out << "    #define LCD_IS_"  << ui->LCD_comboBox->currentText() << " 1\n";
        out << "#endif // #ifdef HAS_LCD\n";
        if ( ui->LED_checkBox->isChecked())
        {
            out << "#ifndef LED_GPIO_Port\n";
            out << "    #define LED_Pin "       << ui->LedName_lineEdit->text() << "_Pin \n";
            out << "    #define LED_GPIO_Port " << ui->LedName_lineEdit->text() << "_GPIO_Port \n";
            out << "#endif\n";
        }
        out << "\n";
        file.close();
    }
}

void ConfigWindow::Generate_Footer()
{
    QFile file(filename);
    QTextStream out(&file);
    if (file.open(QIODevice::Append))
    {
        out << "#define	BOARD_NAME			\"" << ui->BoardName_lineEdit->text()<<"\"\n";
        out << "#define	MACHINE_NAME		\"" << ui->MachineName_lineEdit->text()<<"\"\n";
        out << "#define	MACHINE_VERSION		\"" << ui->MachineVersion_lineEdit->text()<<"\"\n";
        out << "\n";
        out << "#endif /* PROJECT_LIB_MODULES_H_ */\n";
    }
}

void ConfigWindow::on_Generate_UserConfig_pushButton_clicked()
{
    QString filters = "H files (*.h)";
    filename = QFileDialog::getSaveFileName(this, tr("Open user_config.h File"), PROGRAMS_PATH,filters);
    if (filename.isEmpty())
    {
            qDebug() << "Save operation canceled.";
            return;
    }
    Generate_Header();
    Generate_Libraries();
    Generate_Modules();
    Generate_Drivers();
    Generate_Footer();
    qDebug() << "File created successfully!";
}

void ConfigWindow::on_LwIp_checkBox_toggled(bool checked)
{
    if ( checked )
        ui->MQTT_checkBox->setEnabled(true);
    else
        ui->MQTT_checkBox->setEnabled(false);
}
